---
- name: Sample NETCONF config
  hosts: podiosv
  connection: local
  gather_facts: True
  vars_files:
    - var_files/vars.yml

  tasks:

    - name: set ntp server via NETCONF
      netconf_config:
        #host: "{{inventory_hostname}}"
        #username: "{{ansible_user}}"
        hostkey_verify: False
        #password: "{{ansible_ssh_pass}}"
        #port: 830
        xml: |
            <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <ntp>
                  <server xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ntp">
                    <server-list>
                      <ip-address>5.5.5.{{pod}}</ip-address>
                    </server-list>
                  </server>
                </ntp>
              </native>
            </config>
